import re
from typing import Any

def clean_item_name(value: Any, fallback: str = "Travel item") -> str:
    if not isinstance(value, str):
        return fallback

    cleaned = value.strip()
    
    # 1. Scrub leading code comments, bullets, or hyphens (e.g. "// a bit dry")
    cleaned = re.sub(r"^[\-\*\/\.\s]+", "", cleaned)
    
    lowered = cleaned.lower()
    
    # 2. Chop off key bleed artifacts generated by the LLM
    for prefix in ["name:", "item:", "object:", "notes:", "title:", "category:", "description:"]:
        if lowered.startswith(prefix):
            cleaned = cleaned[len(prefix):].strip()
            lowered = cleaned.lower()
            break

    # 3. Aggressive Artifact & Hallucination Filter
    bad_words = {
        "name", "item", "object", "travel item", "packing item", 
        "enumerate", "null", "undefined", "none", "string", "true", "false",
        "yumbrella", "a bit dry"
    }

    if (
        not cleaned
        or lowered in bad_words
        or re.fullmatch(r"item\s*\d+", lowered)
        or "bit dry" in lowered
        or len(cleaned) < 2
    ):
        return fallback

    # 4. Fix AI "Stuttering" (e.g., "Sunglasses Sunglasses" -> "Sunglasses")
    words = cleaned.split()
    if len(words) == 2 and words[0].lower() == words[1].lower():
        cleaned = words[0]

    return " ".join(cleaned.split())


def normalize_key(value: str) -> str:
    return "".join(ch for ch in value.lower().strip() if ch.isalnum())


def clean_category_items(items: list[Any]) -> list[dict]:
    cleaned_items = []

    for index, item in enumerate(items):
        if isinstance(item, str):
            name = clean_item_name(item, "")
            if name:
                cleaned_items.append({
                    "name": name,
                    "quantity": 1,
                    "priority": "useful",
                    "notes": None,
                })
            continue

        if hasattr(item, "model_dump"):
            item = item.model_dump()

        if isinstance(item, dict):
            name = clean_item_name(item.get("name"), "")
            if not name:
                continue

            raw_quantity = item.get("quantity")
            quantity = raw_quantity if isinstance(raw_quantity, int) and raw_quantity > 0 else 1

            priority = item.get("priority")
            if priority not in {"critical", "useful", "optional"}:
                priority = "useful"

            notes = item.get("notes")
            if isinstance(notes, str):
                notes = notes.strip()
                # Remove leading // from notes
                notes = re.sub(r"^[\-\*\/\.\s]+", "", notes) 
                
                if notes.lower().startswith("notes:"):
                    notes = notes[6:].strip() # Chop off "notes:"
                    
                if not notes or notes.lower() in ["null", "none", "undefined", "n/a", "a bit dry"]:
                    notes = None

            cleaned_items.append({
                **item, 
                "name": name,
                "quantity": quantity,
                "priority": priority,
                "notes": notes, 
            })

    return cleaned_items


def clean_categories(categories: list[Any]) -> list[dict]:
    cleaned_categories = []
    
    # Global Deduplication Tracker
    global_seen_items = set() 

    for index, category in enumerate(categories):
        if not isinstance(category, dict):
            continue

        name = clean_item_name(category.get("name"), f"Category {index + 1}")
        items = clean_category_items(category.get("items") or [])

        # Filter duplicates before adding them to the final output
        deduplicated_items = []
        for item in items:
            item_key = normalize_key(item["name"])
            
            if item_key not in global_seen_items and item["name"].lower() != "travel item":
                global_seen_items.add(item_key)
                deduplicated_items.append(item)

        if not deduplicated_items:
            continue

        cleaned_categories.append({
            **category,
            "name": name,
            "items": deduplicated_items,
        })

    return cleaned_categories


def sanitize_ai_response(payload: dict) -> dict:
    """
    🛡️ GLOBAL POST-PROCESSOR PIPELINE 🛡️
    Intercepts the raw JSON from the LLM and aggressively cleans artifacts, 
    hallucinations, and duplicates before it reaches the node logic.
    """
    sanitized = dict(payload)

    # 1. Clean and deduplicate 'updated_draft' categories and root properties
    draft = sanitized.get("updated_draft")
    if draft and isinstance(draft, dict):
        
        # Scrub root-level string artifacts (Fixes "null" strings and trailing spaces on dates)
        for k, v in list(draft.items()):
            if isinstance(v, str):
                clean_v = v.strip()
                if clean_v.lower() in ["null", "none", "undefined", "n/a", ""]:
                    draft[k] = None
                else:
                    draft[k] = clean_v
                    
        # Now clean categories
        categories = draft.get("categories")
        if categories and isinstance(categories, list):
            draft["categories"] = clean_categories(categories)
    
    # 2. Clean and deduplicate 'suggestionAction' itemNames (for active trips)
    action = sanitized.get("suggestionAction")
    if action and isinstance(action, dict):
        if action.get("type") == "add-items" and action.get("label") == "Left to Pack":
            action["type"] = "unpacked-checklist"
            clean_names = []
            for name in action.get("itemNames", []):
                clean_name = re.sub(r"\s*\([+xX]?\s*\d+\)$", "", name).strip()
                clean_names.append(clean_name)
            action["itemNames"] = clean_names

        item_names = action.get("itemNames")
        if item_names and isinstance(item_names, list):
            clean_names = []
            seen = set()
            for name in item_names:
                cleaned = clean_item_name(name, "")
                item_key = normalize_key(cleaned)
                if cleaned and item_key not in seen:
                    seen.add(item_key)
                    clean_names.append(cleaned)
            action["itemNames"] = clean_names
        
        # Clean 'items' array if it's a category review action
        review_items = action.get("items")
        if review_items and isinstance(review_items, list):
            action["items"] = clean_category_items(review_items)

    return sanitized