from pydantic import BaseModel, Field, field_validator
from typing import List, Literal, Optional, Dict, Any


class GeneratedItem(BaseModel):
    """An individual item generated by the AI for the packing list or review card."""
    name: str = Field(description="The name of the item to pack")
    quantity: Optional[int] = Field(default=1, description="How many of this item to bring")
    priority: Optional[Literal['critical', 'useful', 'optional']] = Field(
        default='useful', 
        description="The priority level of the item"
    )
    notes: Optional[str] = Field(default=None, description="Optional advice or context for this item")
    @field_validator("name")
    @classmethod
    def clean_name(cls, value: str) -> str:
        cleaned = value.strip()

        lowered = cleaned.lower()
        for prefix in ["name:", "item:", "object:"]:
            if lowered.startswith(prefix):
                cleaned = cleaned[len(prefix):].strip()
                break

        if not cleaned or cleaned.lower() in {"name", "item", "object", "travel item"}:
            return ""

        return " ".join(cleaned.split())

class GeneratedCategory(BaseModel):
    """A category containing multiple packing items."""
    name: str = Field(description="The name of the category (e.g., 'Clothing', 'Toiletries')")
    items: List[GeneratedItem] = Field(description="List of items belonging to this category")
    @field_validator("name")
    @classmethod
    def clean_category_name(cls, value: str) -> str:
        cleaned = value.strip()

        lowered = cleaned.lower()
        for prefix in ["name:", "category:", "title:"]:
            if lowered.startswith(prefix):
                cleaned = cleaned[len(prefix):].strip()
                break

        if not cleaned or cleaned.lower() in {"name", "category", "title"}:
            return "Packing"

        return " ".join(cleaned.split())


class TripDraftConfig(BaseModel):
    """The dynamic delta parameters object extracted from user input or images."""
    destination: Optional[str] = Field(default=None, description="The extracted name of the target destination")
    tripVibe: Optional[str] = Field(default=None, description="The extracted travel vibe style (e.g., beach, business, camping, citybreak)")
    packingStyle: Optional[str] = Field(default=None, description="The extracted preference style (e.g., light traveler, balanced, prepared pro)")
    startDate: Optional[str] = Field(default=None, description="The start date of the trip in YYYY-MM-DD format")
    endDate: Optional[str] = Field(default=None, description="The end date of the trip in YYYY-MM-DD format")
    fromLocation: Optional[str] = Field(default=None, description="The starting location or departure city")
    
    categories: Optional[List[GeneratedCategory]] = Field(
        default=None, 
        description="The fully generated packing categories and items. Populate this when the draft is complete."
    )
    
    picoReviewStatus: Optional[Literal["reviewing", "readyToSave"]] = Field(
        default=None,
        description="Internal Ask Pico review status for the generated packing list.",
    )

    picoReviewIndex: Optional[int] = Field(
        default=None,
        description="Zero-based index of the category currently being reviewed.",
    )



class PackedItemContext(BaseModel):
    """A lightweight representation of an item currently in the user's bag."""
    name: str = Field(description="The name of the item")
    packed: bool = Field(description="Whether the user has checked this item off in their list")
    quantity: Optional[int] = Field(default=1, description="How many of this item are currently in the list")

class TripMetadata(BaseModel):
    """The core trip details needed for Pico to understand the travel context."""
    destination: Optional[str] = Field(default=None, description="The target destination location name")
    durationDays: Optional[int] = Field(default=None, description="Total count of days for the trip")
    tripVibe: Optional[str] = Field(default=None, description="The style of the trip (e.g., beach, business, roadTrip, camping, cityBreak)")
    activities: List[str] = Field(default_factory=list, description="Array of planned trip activities (e.g., hiking, swimming, sightseeing)")

class AttachmentPayload(BaseModel):
    """The binary image or file asset stream sent from the mobile native camera roll/picker."""
    base64_data: str = Field(description="The raw base64 data string of the file asset")
    mime_type: str = Field(default="image/jpeg", description="The standard media mime-type descriptor string")

class ChatRequest(BaseModel):
    """The exact JSON payload your React Native app will send via POST to /api/chat."""
    user_message: str = Field(description="The actual message or question typed by the user")
    
    thread_id: str = Field(default="default_thread", description="Unique identifier for the LangGraph conversation memory")
    
    mode: str = Field(default="general", description="The active context interaction mode ('general', 'activeTrips', 'newTrip')")
    trip_context: Optional[TripMetadata] = Field(
        default=None, 
        description="The route and situational metadata for the current trip. Can be null in general or pre-trip modes."
    )
    current_list: List[PackedItemContext] = Field(
        default_factory=list,
        description="The flattened list of items currently sitting in AsyncStorage along with their packed booleans"
    )
    current_draft: Optional[Dict[str, Any]] = Field(
        default=None,
        description="The current partial configuration state of a brand new trip being set up"
    )
    attachment: Optional[AttachmentPayload] = Field(
        default=None,
        description="An optional vision document or screenshot data payload attached by the user"
    )


class SuggestionAction(BaseModel):
    """
    The actionable data block that tells the React Native UI to render a clickable chip.
    """

    type: Literal['add-items', 'remove-items', 'open-screen', 'none', 'ask-question', 'review-category', 'unpacked-checklist'] = Field(
        default='none',
        description="The action type execution rule. Use 'ask-question' for missing info, 'review-category' for category approval."
    )
    label: str = Field(
        default="",
        description="The text displayed on the UI chip button"
    )
    itemNames: List[str] = Field(
        default=[],
        description="An array of item names to display in the UI (used for adding, removing, or checking off items)."
    )
    kind: Optional[Literal['general', 'almostForgot']] = Field(
        default=None,
        description="Optional tag categorization for tracking specific feature workflows"
    )
    route: Optional[str] = Field(
        default=None,
        description="Optional frontend route for open-screen actions.",
    )
    

    categoryName: Optional[str] = Field(default=None, description="The name of the category being reviewed")
    categoryIndex: Optional[int] = Field(default=None, description="The current index of the category being reviewed (1-based)")
    totalCategories: Optional[int] = Field(default=None, description="Total number of categories to review")
    items: Optional[List[GeneratedItem]] = Field(default=None, description="The list of items for the user to review in this category")

class PicoResponseSchema(BaseModel):
    """
    The exact JSON structure Gemini MUST output. 
    """
    content: str = Field(
        description="Pico's friendly, conversational, mascot-toned text response bubble explaining the advice"
    )
    suggestionAction: SuggestionAction = Field(
        default_factory=lambda: SuggestionAction(type='none', label='', itemNames=[], kind=None),
        description="The corresponding interactive suggestion payload for the message block"
    )
    updated_draft: Optional[TripDraftConfig] = Field(
        default=None, 
        description="The dynamic delta parameters object extracted from user input to merge with the frontend draft store"
    )